version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: react-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"  # Change port from 3000 to 8080
    stdin_open: true
    tty: true

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Expose port 80 for external access
    depends_on:
      - backend
      - frontend
